name: Deploy Frontend to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout the repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2 Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      # 3 Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # 4 Install dependencies
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # 5 Build the project
      - name: Build Project
        run: pnpm run build

      # 6 Remove existing dist folder on server
      - name: Clean old dist folder
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Cleaning old dist folder..."
            rm -rf ${{ secrets.APP_DIRECTORY }}/dist

      # 7 Upload build files
      - name: Upload Build to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist"
          target: "${{ secrets.APP_DIRECTORY }}"

      # 8 Update environment file
      - name: Update Environment File
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.APP_DIRECTORY }}
            echo "API_URL=https://expresscronjob.com/api" > .env

      # 9 Reload NGINX
      - name: Reload NGINX
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl reload nginx
